/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metier.modele;

/**
 *
 * @author ypeyrot
 */
public enum Matiere {
    // Collège (6e à 3e)
    FRANCAIS_COLLEGE,
    MATHEMATIQUES_COLLEGE,
    HISTOIRE_GEOGRAPHIE_COLLEGE,
    SCIENCES_SVT_COLLEGE,
    SCIENCES_PHYSIQUE_CHIMIE_COLLEGE,
    TECHNOLOGIE_COLLEGE,
    LANGUES_VIVANTES_COLLEGE,
    EDUCATION_PHYSIQUE_SPORTIVE_COLLEGE,
    ARTS_PLASTIQUES_COLLEGE,
    EDUCATION_MUSICALE_COLLEGE,
    EDUCATION_CIVIQUE_COLLEGE,
    INFORMATIQUE_NUMERIQUE_COLLEGE,

    // Lycée (Seconde à Terminale)
    FRANCAIS_LYCEE,
    MATHEMATIQUES_LYCEE,
    HISTOIRE_GEOGRAPHIE_LYCEE,
    SCIENCES_SVT_LYCEE,
    SCIENCES_PHYSIQUE_CHIMIE_LYCEE,
    LANGUE_VIVANTE_1_LYCEE,
    LANGUE_VIVANTE_2_LYCEE,
    EDUCATION_PHYSIQUE_SPORTIVE_LYCEE,
    PHILOSOPHIE_LYCEE,
    EDUCATION_CIVIQUE_JURIDIQUE_SOCIALE_LYCEE,
    ACCOMPAGNEMENT_PERSONNALISE_LYCEE,

    // Spécialités en Première (générale)
    SCIENCES_ECONOMIQUES_SOCIALES_LYCEE,
    INFORMATIQUE_CREATION_NUMERIQUE_LYCEE,
    ARTS_PLASTIQUES_LYCEE,
    MUSIQUE_LYCEE,
    SCIENCES_ET_LABORATOIRE_LYCEE,

    // Spécialités en Terminale (générale)
    PHILOSOPHIE_TERMINALE,
    SCIENCES_ECONOMIQUES_SOCIALES_TERMINALE,
    SCIENCES_SVT_TERMINALE,
    PHYSIQUE_CHIMIE_TERMINALE,
    ARTS_TERMINALE,
    
    // Lycée Technologique (exemples)
    SCIENCES_TECHNOLOGIES_INDUSTRIE_DEVELOPPEMENT_DURABLE,
    SCIENCES_TECHNOLOGIES_SANTE_SOCIAL,
    SCIENCES_TECHNOLOGIES_MANAGEMENT_GESTION;
}